### ISSUE TITLE
Create update a poll page (Backend)

### ISSUE THREAD

**Issue by binamkayastha** [SocietyClub/RCV#16]
## User Story:
As a Poll Creator, I would like to be able to update a poll title and/or candidates, because I would like to fix any mistakes I may have made.
As a Poll Creator, I would like the poll to only be editable by me, because I want to prevent others from tampering with my poll settings.
As a Poll Creator, I would like to retain the poll link when I update a poll, because I want to avoid sending a new poll link.

## [Figma Design](https://www.figma.com/file/oYqBbDmkuO5OJZO7qP7AX7/SocietyClub-Ranked-Choice-Voting?node-id=26%3A6308)
![Figma Image](https://user-images.githubusercontent.com/12178490/126079459-618ea103-64e8-4d65-8afc-dee47d0c3355.png)

## Acceptance Criteria:
 - [x] Backend API call update to the DB Table Poll
 - [x] Return the Poll Details to the User
 - [x] Only allow the poll creator to make changes (based on the poll creator id). Return unauthorized code 
 - [x] The poll Id is the same

**Comment by godeva** [comment]
[updatePoll Pull Request](https://github.com/SocietyClub/RCV-backend/pull/19)
