### ISSUE TITLE
On ViewPoll page, implement `Share Poll` button

### ISSUE THREAD

**Issue by binamkayastha** [SocietyClub/RCV#19]
## User Story:
As a Poll Creator, I would like to retain the poll link when I update a poll, because I want to avoid sending a new poll link.
As a Poll Creator, I would like to have a button I can click that will give me a separate link to share to the voters, because I want to be able to share my poll with others. 
As a Voter, I would like to be able to join a poll by going to a given link, because I would like to vote.

## [Figma Design](https://www.figma.com/file/oYqBbDmkuO5OJZO7qP7AX7/SocietyClub-Ranked-Choice-Voting?node-id=26%3A6096)
![image](https://user-images.githubusercontent.com/12178490/126493905-898b072d-2d20-4a14-8adc-145b50fc0a1b.png)
![image](https://user-images.githubusercontent.com/12178490/126493928-41e5f99f-466b-4676-bb75-100eedd42bff.png)

## Acceptance Criteria:
 - [ ] Implement a the share button
 - [ ] Update design file to use a share modal instead of a snackbar
 - [ ] When the poll creator clicks `share` on the poll page, show a share modal

**Comment by CoryTapply** [comment]
I ended up just making the Share button copy the link to the poll to the user's clipboard. I think if we wanted to to like connections to share via Facebook or Twitter we can in the future but probably not necessary for MVP

**Comment by binamkayastha** [comment]
Nice thank you
Cleaning up some issues
This is done
