### ISSUE TITLE
Flush out details on an Landing Page Style Info page

### ISSUE THREAD

**Issue by CoryTapply** [SocietyClub/RCV#20]
Todo after MVP.
This ticket may need to be split into more in the future

Possibly take the onboarding guide/intro to RCV text and add it to the landing page: https://discord.com/channels/837121733139497011/837478108693135400/839623856893329488

AC:
 - [ ] Create some mockup for the landing page
 - [ ] Design should be interactive and easy to understand

**Comment by binamkayastha** [comment]
Completed by Goutham
Design: https://docs.google.com/drawings/d/1A8xc7I8DjY3dTtxKPm9IDOaqWSRUMamqa_MGFO9zDXE/edit
Feel free to update the frontpage with a new design though if you're up for it later
